rules:
  unpinned-uses:
    config:
      policies:
        "*": hash-pin
        actions/*: any
        grafana/*: any
  forbidden-uses:
    config:
      deny:
        # Policy-banned by our security team due to CVE-2025-30066 & CVE-2025-30154.
        # https://www.cisa.gov/news-events/alerts/2025/03/18/supply-chain-compromise-third-party-tj-actionschanged-files-cve-2025-30066-and-reviewdogaction
        # https://nvd.nist.gov/vuln/detail/cve-2025-30066
        # https://nvd.nist.gov/vuln/detail/cve-2025-30154
        - reviewdog/*
