{
 "title": "xk6-dashboard",
 "time": { "from": "2023-09-06T13:19:30.000Z", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "iteration rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(k6_iterations_total[$__rate_interval])), 0.1)"
    }
   ]
  },
  {
   "title": "VUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "k6_vus" }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(k6_http_req_duration_avg[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Received Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_received_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_sent_total[10s]))"
    }
   ]
  },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "k6_vus" }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_sent_total[$__rate_interval]))"
    },
    {
     "expr": "sum(rate(k6_data_received_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "HTTP Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(k6_http_req_duration_avg[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_duration_p90[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_duration_p95[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Iteration Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(k6_iteration_duration_avg[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_iteration_duration_p90[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_iteration_duration_p95[$__rate_interval]))"
    }
   ]
  },
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(k6_http_req_duration_avg[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_duration_p90[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_duration_p95[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "HTTP Request Waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(k6_http_req_waiting_avg[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_waiting_p90[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_waiting_p95[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "HTTP Request TLS handshaking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(k6_http_req_tls_handshaking_avg[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_tls_handshaking_p90[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_tls_handshaking_p95[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "HTTP Request Sending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(k6_http_req_sending_avg[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_sending_p90[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_sending_p95[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "HTTP Request Connecting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(k6_http_req_connecting_avg[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_connecting_p90[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_connecting_p95[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "HTTP Request Receiving",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(k6_http_req_receiving_avg[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_receiving_p90[$__rate_interval]))"
    },
    {
     "expr": "avg(rate(k6_http_req_receiving_p95[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true
  }
 ]
}